nameOverride: ""
fullnameOverride: ""

prometheus:
  enabled: true
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1000m
        
    retention: 10d
    retentionSize: "9GiB"
    
    podMonitorSelector: {}
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
  additionalServiceMonitors:
  - name: "myapp-task2"
    selector:
      matchLabels:
        metrics: "true"
    namespaceSelector:
      any: true
    endpoints:
      - port: "http"
        interval: 30s
        path: /metrics

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m
    # secrets:
    #   - telegram-bot-secret
  config:
    # telegram_api_url: "https://api.telegram.org" 
    global:
      telegram_api_url: "https://api.telegram.org" 
      resolve_timeout: 5m
      
    route:
      receiver: 'telegram'
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      routes:
      - receiver: 'telegram'
        match:
          severity: critical

    receivers:
    - name: 'telegram'
      webhook_configs:
      - url: 'https://api.telegram.org/bot8267216338:AAFLL7IWr8J-v8pKtKNeASkm92sJWj3q-2Y/sendMessage?chat_id=-5005806102&parse_mode=HTML&text={{ .Status | toUpper }}%20Alert%3A%20{{ .CommonLabels.alertname | urlquery }}'
        send_resolved: true
        max_alerts: 5 
        http_config: {}
        message: '{{ template "telegram.message" . }}'
        # url_fields:
        #   chat_id: "-5005806102"  # ID чата/канала 
        #   parse_mode: "HTML" 
          # body: |
          #   {
          #     "chat_id": "-5005806102",
          #     "text": "🚨 *Alert:* {{ .GroupLabels.alertname }}\n\n{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}",
          #     "parse_mode": "Markdown"
          #   }
    templates:
    - '/etc/alertmanager/templates/*.tmpl'
  templateFiles:
    telegram.tmpl: |
      {{ define "telegram.message" }}
      {{ if eq .Status "firing" }}🚨{{ else }}✅{{ end }} <b>{{ .Status | toUpper }}</b>
      {{ range .Alerts }}
    
      🔥<b>{{ .Annotations.summary }}</b>
      📝 {{ .Annotations.description }}
    
      📌 <b>Alert:</b> {{ .Labels.alertname }}
      🏷️ <b>Severity:</b> {{ .Labels.severity | default "warning" }}
      📍 <b>Instance:</b> {{ .Labels.instance | default "N/A" }}
      📦 <b>Namespace:</b> {{ .Labels.namespace | default "N/A" }}
      🏷️ <b>Pod:</b> {{ .Labels.pod | default "N/A" }}
      🕒 <b>Started:</b> {{ .StartsAt.Format "2006-01-02 15:04:05" }}
    
      {{ if .Annotations.runbook_url }}
      📖 <b>Runbook:</b> {{ .Annotations.runbook_url }}
      {{ end }}
    
      {{ if .Annotations.dashboard }}
     📊 <b>Dashboard:</b> {{ .Annotations.dashboard }}
      {{ end }}
      {{ end }}
      {{ end }}

grafana:
  enabled: true
  adminPassword: "admin"
  persistence:
    enabled: true
    size: 5Gi
    accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.logs.svc.cluster.local:3100

prometheusOperator:
  enabled: true
  crds:
    enabled: false
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

nodeExporter:
  enabled: true

kube-state-metrics:
  enabled: true

serviceAccounts:
  create: true
  automount: true