nameOverride: ""
fullnameOverride: ""

prometheus:
  enabled: true
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1000m
        
    retention: 10d
    retentionSize: "9GiB"
    
    podMonitorSelector: {}
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
  additionalServiceMonitors:
  - name: "myapp-task2"
    selector:
      matchLabels:
        metrics: "true"
    namespaceSelector:
      any: true
    endpoints:
      - port: "http"
        interval: 30s
        path: /metrics

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m
    # secrets:
    #   - telegram-bot-secret
  config:
    global:
      resolve_timeout: 5m
      
    route:
      receiver: 'telegram'
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      routes:
      - receiver: 'telegram'
        match:
          severity: critical

    receivers:
    - name: 'telegram'
      telegram_configs:
      - bot_token: '8267216338:AAFLL7IWr8J-v8pKtKNeASkm92sJWj3q-2Y'
        chat_id: -5005806102
        parse_mode: 'HTML'
        send_resolved: true
        message: '{{ template "telegram.default.message" . }}'
    templates:
    - '/etc/alertmanager/templates/*.tmpl'

  templateFiles:
    telegram.tmpl: |
      {{ define "telegram.default.message" -}}
      {{- if eq .Status "firing" }}🚨{{ else }}✅{{ end }} <b>{{ .Status | toUpper }}</b> - {{ .GroupLabels.alertname | default "Alert" }}
  
      📊 <b>Affected Services:</b>
      {{- range $index, $alert := .Alerts }}
      {{- if eq $index 0 }} {{ else }}, {{ end }}
      {{ $alert.Labels.service | default $alert.Labels.job }}
      {{- end }}
  
      📦 <b>Namespaces:</b>
      {{- $namespaces := list -}}
      {{- range .Alerts -}}
        {{- $ns := .Labels.namespace -}}
        {{- if and $ns (not (in $namespaces $ns)) -}}
          {{- $namespaces = append $namespaces $ns -}}
        {{- end -}}
      {{- end -}}
      {{- range $index, $ns := $namespaces -}}
        {{- if eq $index 0 }} {{ else }}, {{ end }}{{ $ns }}
      {{- end }}
  
      🔥 <b>Main Issue:</b>
      {{- with index .Alerts 0 }}
      {{ .Annotations.summary }}
      {{- end }}
  
      ─────────────────────
      <b>Details:</b>
      {{- range .Alerts }}
  
      • <b>{{ .Labels.service | default .Labels.job }}</b> ({{ .Labels.namespace }})
        {{ .Annotations.description }}
      {{- end }}
  
      🕒 <b>Alert Time:</b> {{ (index .Alerts 0).StartsAt.Format "15:04:05" }}
      🔢 <b>Total Instances:</b> {{ len .Alerts }}
      {{- end }}

grafana:
  enabled: true
  adminPassword: "admin"
  persistence:
    enabled: true
    size: 5Gi
    accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.logs.svc.cluster.local:3100

prometheusOperator:
  enabled: true
  crds:
    enabled: false
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

nodeExporter:
  enabled: true

kube-state-metrics:
  enabled: true

serviceAccounts:
  create: true
  automount: true