apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-vault
  namespace: vault
spec:
  project: default
  source:
    repoURL: https://github.com/KatyaPikta/infra-argo.git
    targetRevision: HEAD
    chart: charts/vault
    helm:
      valueFiles:
      - values/vault/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      