config:
  clients:
    - url: http://loki:3100/loki/api/v1/push
  snippets:
    pipelineStages:
      - cri: {}
      - docker: {}
      - json:
          expressions:
            level: ""
      - regex:
          expression: 'level=(?P<level>\w+)'
      - regex:
          expression: '^\[\d{2}:\d{2}:\d{2} (?P<level>[A-Z]{3})\]'
      - template:
          source: level
          template: >-
            {{- if eq .Value "INF" -}}info
            {{- else if eq .Value "WRN" -}}warn
            {{- else if eq .Value "ERR" -}}error
            {{- else -}}{{ .Value }}{{ end }}
          output: level
      - labels:
          level: null
