config:
  clients:
    - url: http://loki.logs.svc.cluster.local:3100/loki/api/v1/push
  
  snippets:
    scrapeConfigs: |
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
        - role: pod
        pipeline_stages:
        - cri: {}
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_logging_loki_io_enabled]
          action: keep
          regex: "true"
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container
        - source_labels: [__meta_kubernetes_pod_node_name]
          target_label: node
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_label_app]
          target_label: app

daemonset:
  enabled: true

serviceAccount:
  create: true
  annotations: {}

# Ресурсы
resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 500m
