apiVersion: v2
name: task2
description: A Helm chart for Kubernetes
type: application
version: 1.5.12
appVersion: "82436aeafc8ccc8624f79d6e8fd254d6656a0bbe"
# dependencies:
# - condition: frontend.enabled
#   name: frontend
#   repository: ""
# - condition: backend.enabled
#   name: backend
#   repository: ""
# - condition: mysql.enabled
#   name: mysql
#   repository: https://charts.bitnami.com/bitnami
#   version: 8.0.0
# - condition: redis.enabled
#   name: redis
#   repository: https://charts.bitnami.com/bitnami
#   version: 17.0.0
