apiVersion: v2
name: task2
description: A Helm chart for Kubernetes
type: application
version: 1.5.7
appVersion: "d07e4ec29f22a11ccaee89b9c128cc24bbe769f4"
# dependencies:
# - condition: frontend.enabled
#   name: frontend
#   repository: ""
# - condition: backend.enabled
#   name: backend
#   repository: ""
# - condition: mysql.enabled
#   name: mysql
#   repository: https://charts.bitnami.com/bitnami
#   version: 8.0.0
# - condition: redis.enabled
#   name: redis
#   repository: https://charts.bitnami.com/bitnami
#   version: 17.0.0
