mysql:
  persistence:
    storageClass: "do-block-storage"

redis:
  persistence:
    storageClass: "do-block-storage"

frontend:
  image:
    tag: "afaf837a6ba4b5b2b90bf69b81aabd5063ad0915"

backend:
  image:
    tag: "afaf837a6ba4b5b2b90bf69b81aabd5063ad0915"