fullnameOverride: "external-secrets"
namespace: "external-secret"

installCRDs: false

clusterSecretStore:
  enabled: true
  name: vault-backend
  vaultServer: "http://hashicorp-vault.vault:8200"
  vaultPath: secret
  kubernetes:
    mountPath: kubernetes
    role: external-secrets
    serviceAccountName: external-secrets
    serviceAccountNamespace: external-secret

externalSecrets:
  grafana-admin-secret:
    enabled: true
    namespace: monitoring
    name: grafana-admin-secret
    remoteKey: secret/monitoring/grafana
  telegram-bot-secret:
    enabled: true
    namespace: monitoring
    name: telegram-bot-secret
    remoteKey: secret/telegram/bot
