namespaces:

  - name: "myapp-task2"
    labels:
      kubernetes.io/metadata.name: myapp-task2
      environment: "production"

  - name: "myapp-task2-staging"
    labels:
      kubernetes.io/metadata.name: myapp-task2-staging
      environment: "staging"

resourceQuotas:
  enabled: false

limitRanges:
  enabled: false

# resourceQuotas:
#   enabled: true
#   default:
#     requests.cpu: "1"
#     requests.memory: "2Gi"
#     limits.cpu: "2"
#     limits.memory: "4Gi"
#     pods: "20"

# limitRanges:
#   enabled: true
#   default:
#     default:
#       cpu: "500m"
#       memory: "1Gi"
#     defaultRequest:
#       cpu: "200m"
#       memory: "512Mi"