apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-myapp-backup
  namespace: backup
spec:
  schedule: "37 17 * * *"
  template:
    includedNamespaces:
    - myapp-task2
    - cert-manager
    - argocd
    - traefik
    includedResources:
      - "*"
    excludedResources:
      - nodes
      - events
      - events.events.k8s.io
      - backups.velero.io
      - restores.velero.io
      - resticrepositories.velero.io
    snapshotVolumes: true
    defaultVolumesToFsBackup: true
    ttl: 720h
    storageLocation: default
    volumeSnapshotLocations:
    - default